# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: aheuermann/electron

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

# Honestly this is pretty useless. But at least I get to know if the linux build fails.

cache:
  paths:
  - node_modules/

# before_script:
#   - apt-get install xvfb
#   - "export DISPLAY=:99.0"
#   - "sh -e xvfb start"
#   - sleep 3

test:
  stage: test
  script:
    - npm install
    - node_modules/.bin/mocha

# build:
#   stage: build
#   script:
#    - npm install
#    - node_modules/.bin/electron-builder --dir && node_modules/.bin/electron-builder --linux